name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: 18.0.0
      - name: Install NPM
        run: |
          npm ci
          npm install
      - name: NPM run format
        run: |
          npm run format
          npm run lint
